trigger:
  - master

pool:
  vmImage: ubuntu-latest


steps:
  - checkout: self

  - script: | 
      latest_version=$(curl -Is "https://github.com/snyk/cli/releases/latest" | grep "^location" | sed s#.*tag/##g | tr -d "\r")
      echo "Latest Jira-tickets-new-vulns Version: ${latest_version}"
      curl -LO "https://github.com/snyk/cli/releases/download/${latest_version}/snyk-linux"
      chmod +x snyk-linux
      mv snyk-linux snyk
      ls -la 
    continueOnError: true
    displayName: "Download snyk binary"
  
  - script: |
      ./snyk test --all-projects || True
    #continueOnError: true
    displayName: 'snyk open source'
    
    env: 
       SNYK_TOKEN: $(SNYK_TOKEN)